### ISSUE TITLE
Questions about the StaminaRegenRate value.

### ISSUE THREAD

**Issue by NianBroken** [ItzRock/LongerSprinting#1]
For endurance recovery speed, is the higher the value of "StaminaRegenRate", the faster the recovery?  Or the smaller the value of StaminaRegenRate, the faster the recovery?

**Comment by ItzRock** [comment]
It's supposed to modify the value in the player controller which I've discovered, doesn't do anything so I need release an update which makes recovery faster. The intended purpose was for a higher value for higher recovery.

**Comment by ItzRock** [comment]
Fixed issue, Higher is now for sure faster.
